seed: 0
log_dir: "./log"
notes: "swiss_roll"
run_name: "Nonlinear Control"

data:
  test_ratio: 0.2
  num_episodes: 1000
  action_repeat: 2

env:
  name: swiss_roll
  horizon: 100
  periodic: False

  A:
    - [1.0, 0.0]
    - [0.0, 1.0]
  B:
    - [0.1,0.0]
    - [0.0, 0.1]
  Ns:
    - [0.0001, 0.0]
    - [0.0, 0.0001]
  "No":
    - [0.0001, 0.0, 0.0]
    - [0.0, 0.0001, 0.0]
    - [0.0, 0.0, 0.0001]

train:
  backbone:
    num_updates: 2000
    test_interval: 10
    x_dim: 2
    a_dim: 2
    hidden_dim: 128
    rnn_hidden_dim: 64
    rnn_input_dim: 64
    min_var: 1e-2
    chunk_length: 32
    batch_size: 128
    lr: 1e-3
    eps: 1e-8
    weight_decay: 1e-6
    clip_grad_norm: 1.0
    disable_gpu: True
    kl_beta: 1.0
    free_nats: 3.0

evaluation:
  num_points: 1
  num_regions: 1
  planning_horizon: 8